name: Cola
favicon: null
layout_spectrum: 1
typography_spectrum: 0.6397849
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fdfdfd'
    - '#020801'
    - '#08450e'
    - '#82a0b6'
    - '#576659'
  brandStrength: 0
  lightness: 0.6875
  saturation: 1
  rhythmicContrast: 0
purpose: []
