name: Cola
favicon: null
layout_spectrum: 0.50819
typography_spectrum: 0.6397849
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010103'
    - '#454249'
    - '#d78c48'
    - '#8b8b7f'
    - '#fbeced'
  brandStrength: 0.6875
  lightness: 0.625
  saturation: 0.1875
  rhythmicContrast: 1
purpose: []
