name: Cola
favicon: null
layout_spectrum: 0.50819
typography_spectrum: 0.6397849
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fdfdfd'
    - '#020801'
    - '#08450e'
    - '#82a0b6'
    - '#576659'
  brandStrength: 0.8125
  lightness: 0.5
  saturation: 0.1875
  rhythmicContrast: 1
purpose: []
