name: Cola
favicon: null
layout_spectrum: 0.4641577
typography_spectrum: 0.6397849
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#6F86B5'
    - '#274B16'
    - '#020301'
    - '#D0E8D0'
    - '#BBE15B'
  brandStrength: 0.5625
  lightness: 0.6666667
  saturation: 0.75
  rhythmicContrast: 1
purpose: []
