layout_spectrum: 0.4641577
color:
  saturation: 0.5698925
  brandStrength: 0.4928315
  lightness: 0.6666667
  brandColors:
    - '#6F86B5'
    - '#274B16'
    - '#020301'
    - '#D0E8D0'
    - '#BBE15B'
  rhythmicContrast: 1
typography_spectrum: 0.6397849
name: Cola
